' Test file for cq-vbn-0204: Unsafe DataSet or DataTable in autogenerated serializable type can be vulnerable to remote code execution attacks
' This rule detects autogenerated serializable classes that contain DataSet or DataTable

' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Imports System
Imports System.Data
Imports System.Runtime.Serialization

' Violation: Auto-generated serializable class with DataSet property
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataSetProperty
    Public Property MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Class

' Violation: Auto-generated serializable class with DataTable property
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataTableProperty
    Public Property MyDataTable As DataTable ' Violation - auto-generated + serializable + DataTable
End Class

' Violation: Auto-generated serializable class with DataSet field
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataSetField
    Public MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Class

' Violation: Auto-generated serializable class with DataTable field
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataTableField
    Public MyDataTable As DataTable ' Violation - auto-generated + serializable + DataTable
End Class

' Violation: Auto-generated serializable class with multiple DataSet and DataTable members
<Serializable>
Public Class AutoGeneratedSerializableClassWithMultipleDataMembers
    Public Property DataSet1 As DataSet ' Violation
    Public Property DataTable1 As DataTable ' Violation
    Public DataSet2 As DataSet ' Violation
    Public DataTable2 As DataTable ' Violation
End Class

' Violation: Auto-generated serializable structure with DataSet property
<Serializable>
Public Structure AutoGeneratedSerializableStructWithDataSet
    Public Property MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Structure

' Violation: Auto-generated serializable structure with DataTable field
<Serializable>
Public Structure AutoGeneratedSerializableStructWithDataTable
    Public MyDataTable As DataTable ' Violation - auto-generated + serializable + DataTable
End Structure

' Violation: Auto-generated Friend serializable class with DataSet
<Serializable>
Friend Class AutoGeneratedFriendSerializableClassWithDataSet
    Public Property MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Class

' Violation: Auto-generated serializable class with DataSet and other properties
<Serializable>
Public Class AutoGeneratedSerializableClassWithMixedProperties
    Public Property Name As String
    Public Property Age As Integer
    Public Property MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
    Public Property Description As String
End Class

' Non-violation: Auto-generated serializable class without DataSet or DataTable (should not be detected)
<Serializable>
Public Class AutoGeneratedSafeSerializableClass
    Public Property Name As String
    Public Property Age As Integer
    Public Property Description As String
End Class

' Non-violation: Auto-generated non-serializable class with DataSet (should not be detected)
Public Class AutoGeneratedNonSerializableClassWithDataSet
    Public Property MyDataSet As DataSet ' No violation - not serializable
End Class

' Non-violation: Auto-generated serializable class with private DataSet (should not be detected by this pattern)
<Serializable>
Public Class AutoGeneratedSerializableClassWithPrivateDataSet
    Private myDataSet As DataSet ' No violation - private member
End Class

' Violation: Auto-generated serializable class with DataSet in inheritance scenario
<Serializable>
Public Class AutoGeneratedBaseSerializableClassWithDataSet
    Public Property BaseDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Class

Public Class AutoGeneratedDerivedClass
    Inherits AutoGeneratedBaseSerializableClassWithDataSet
    Public Property DerivedProperty As String
End Class

' Violation: Auto-generated serializable class with DataTable in nested scenario
<Serializable>
Public Class AutoGeneratedOuterSerializableClass
    Public Property OuterDataTable As DataTable ' Violation - auto-generated + serializable + DataTable
    
    <Serializable>
    Public Class NestedSerializableClass
        Public Property NestedDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
    End Class
End Class

' Violation: Auto-generated serializable class with custom DataSet property getter/setter
<Serializable>
Public Class AutoGeneratedSerializableClassWithCustomDataSetProperty
    Private _dataSet As DataSet
    
    Public Property MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
        Get
            Return _dataSet
        End Get
        Set(value As DataSet)
            _dataSet = value
        End Set
    End Property
End Class

' Violation: Auto-generated serializable class with readonly DataTable field
<Serializable>
Public Class AutoGeneratedSerializableClassWithReadOnlyDataTable
    Public ReadOnly MyDataTable As DataTable ' Violation - auto-generated + serializable + DataTable
    
    Public Sub New()
        MyDataTable = New DataTable()
    End Sub
End Class

' Violation: Auto-generated serializable class with shared DataSet field
<Serializable>
Public Class AutoGeneratedSerializableClassWithSharedDataSet
    Public Shared MyDataSet As DataSet ' Violation - auto-generated + serializable + DataSet
End Class

' Violation: Auto-generated serializable class with DataSet array property
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataSetArray
    Public Property DataSets As DataSet() ' Violation - auto-generated + serializable + DataSet
End Class

' Violation: Auto-generated serializable class with DataTable list property
<Serializable>
Public Class AutoGeneratedSerializableClassWithDataTableList
    Public Property DataTables As List(Of DataTable) ' Violation - auto-generated + serializable + DataTable
End Class

' Violation: Auto-generated serializable class with nullable DataSet property
<Serializable>
Public Class AutoGeneratedSerializableClassWithNullableDataSet
    Public Property NullableDataSet As DataSet? ' Violation - auto-generated + serializable + DataSet
End Class

Public Class AutoGeneratedNonSerializableViolations
    
    ' Non-violation: Comments and strings
    Public Sub CommentsAndStrings()
        ' This is about auto-generated <Serializable> Public Class with DataSet property
        Dim message As String = "Auto-generated serializable classes with DataSet can be vulnerable"
        Console.WriteLine("Avoid DataTable in auto-generated serializable types")
    End Sub

End Class
