' Test file for cq-vbn-0203: Ensure autogenerated class containing DataSet.ReadXml() is not used with untrusted data
' This rule detects autogenerated classes that use DataSet.ReadXml

' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>

Imports System
Imports System.Data
Imports System.IO
Imports System.Xml

Public Class AutoGeneratedDataSetViolations
    
    ' Violation: Auto-generated class with ReadXml
    Public Sub ReadXmlFromFile()
        Dim dataSet As New DataSet()
        dataSet.ReadXml("data.xml") ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml from stream
    Public Sub ReadXmlFromStream()
        Dim dataSet As New DataSet()
        Using stream As New FileStream("data.xml", FileMode.Open)
            dataSet.ReadXml(stream) ' Violation - in auto-generated class
        End Using
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml from TextReader
    Public Sub ReadXmlFromTextReader()
        Dim dataSet As New DataSet()
        Using reader As New StreamReader("data.xml")
            dataSet.ReadXml(reader) ' Violation - in auto-generated class
        End Using
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml from XmlReader
    Public Sub ReadXmlFromXmlReader()
        Dim dataSet As New DataSet()
        Using reader As XmlReader = XmlReader.Create("data.xml")
            dataSet.ReadXml(reader) ' Violation - in auto-generated class
        End Using
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml with XmlReadMode
    Public Sub ReadXmlWithMode()
        Dim dataSet As New DataSet()
        dataSet.ReadXml("data.xml", XmlReadMode.ReadSchema) ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with multiple DataSet ReadXml calls
    Public Sub MultipleReadXmlCalls()
        Dim dataSet1 As New DataSet()
        Dim dataSet2 As New DataSet()
        
        dataSet1.ReadXml("data1.xml") ' Violation - in auto-generated class
        dataSet2.ReadXml("data2.xml") ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in loop
    Public Sub ReadXmlInLoop()
        For i As Integer = 0 To 10
            Dim dataSet As New DataSet()
            dataSet.ReadXml($"data{i}.xml") ' Violation - in auto-generated class
        Next
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in conditional
    Public Sub ConditionalReadXml(condition As Boolean)
        Dim dataSet As New DataSet()
        If condition Then
            dataSet.ReadXml("conditional_data.xml") ' Violation - in auto-generated class
        End If
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in Try-Catch
    Public Sub ReadXmlInTryCatch()
        Try
            Dim dataSet As New DataSet()
            dataSet.ReadXml("data.xml") ' Violation - in auto-generated class
        Catch ex As Exception
            Console.WriteLine("Error occurred")
        End Try
    End Sub
    
    ' Violation: Auto-generated class with DataSet field ReadXml
    Private dataSet As New DataSet()
    
    Public Sub FieldDataSetReadXml()
        dataSet.ReadXml("field_data.xml") ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with DataSet parameter ReadXml
    Public Sub ParameterDataSetReadXml(ds As DataSet)
        ds.ReadXml("parameter_data.xml") ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml with variable assignment
    Public Sub ReadXmlWithVariable()
        Dim dataSet As DataSet
        dataSet = New DataSet()
        dataSet.ReadXml("variable_data.xml") ' Violation - in auto-generated class
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in method return context
    Public Function ReadXmlAndReturnDataSet() As DataSet
        Dim dataSet As New DataSet()
        dataSet.ReadXml("return_data.xml") ' Violation - in auto-generated class
        Return dataSet
    End Function
    
    ' Non-violation: Auto-generated class with DataSet without ReadXml (should not be detected)
    Public Sub SafeDataSetOperations()
        Dim dataSet As New DataSet()
        dataSet.DataSetName = "SafeDataSet"
        Dim table As New DataTable("SafeTable")
        dataSet.Tables.Add(table)
    End Sub
    
    ' Non-violation: Comments and strings mentioning ReadXml
    Public Sub CommentsAndStrings()
        ' This is a comment about dataSet.ReadXml
        Dim message As String = "DataSet.ReadXml can be dangerous with untrusted input"
        Console.WriteLine("Use dataSet.ReadXml carefully in auto-generated code")
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in Select Case
    Public Sub ReadXmlInSelectCase(option As Integer)
        Dim dataSet As New DataSet()
        Select Case option
            Case 1
                dataSet.ReadXml("option1_data.xml") ' Violation - in auto-generated class
            Case 2
                dataSet.ReadXml("option2_data.xml") ' Violation - in auto-generated class
            Case Else
                dataSet.ReadXml("default_data.xml") ' Violation - in auto-generated class
        End Select
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml with Using statement
    Public Sub ReadXmlWithUsing()
        Using dataSet As New DataSet()
            dataSet.ReadXml("using_data.xml") ' Violation - in auto-generated class
        End Using
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml in While loop
    Public Sub ReadXmlInWhileLoop()
        Dim counter As Integer = 0
        While counter < 5
            Dim dataSet As New DataSet()
            dataSet.ReadXml($"while_data_{counter}.xml") ' Violation - in auto-generated class
            counter += 1
        End While
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml with MemoryStream
    Public Sub ReadXmlWithMemoryStream()
        Dim dataSet As New DataSet()
        Dim xmlData As Byte() = System.Text.Encoding.UTF8.GetBytes("<root><item>data</item></root>")
        Using stream As New MemoryStream(xmlData)
            dataSet.ReadXml(stream) ' Violation - in auto-generated class
        End Using
    End Sub
    
    ' Violation: Auto-generated class with DataSet ReadXml with StringReader
    Public Sub ReadXmlWithStringReader()
        Dim dataSet As New DataSet()
        Dim xmlString As String = "<root><item>data</item></root>"
        Using reader As New StringReader(xmlString)
            dataSet.ReadXml(reader) ' Violation - in auto-generated class
        End Using
    End Sub

End Class
